### ISSUE TITLE
funny characters in citations (likely a utf8 encoding issue) 

### ISSUE THREAD

**Issue by jhpoelen** [seltmann/bee-interaction-database#1]
first: thanks for letting your species interaction data be indexed by GloBI! Cool to see some more bee interactions be transcribed from literature.

I noticed some funny characters in source literature citations. 

For instance, I noticed:

```Severns, P. M. & Moldenke, A. R. (2010) Management tradeoffs between focal species and biodiversity: Endemic plant conservation and solitary bee extinction. Biodivers. Conserv. 19, 3605�3609```

with ```3605�3609``` that has the funny character. 

If you make sure to import/enter/save your csv/tsv tables using UTF8 encoding, this issue is likely not to occur. See also attached screenshot from https://www.globalbioticinteractions.org/references.html?accordingTo=globi%3Aglobalbioticinteractions%2Fbee-interaction-database&interactionType=ecologicallyRelatedTo 

![Screenshot from 2020-04-14 12-11-31](https://user-images.githubusercontent.com/1084872/79264908-27490d00-7e4a-11ea-9a3c-12acfec702b6.png)

**Comment by seltmann** [comment]
Castaeda-Vildzola,
